//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "FacebookDialog.xaml.h"
#include "FacebookProfilePictureControl.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "FacebookDialog.g.hpp"
#include "FacebookProfilePictureControl.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_CropMode(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->CropMode);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Permissions(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Permissions;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_UserId(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->UserId;
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_CropMode(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->CropMode = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Permissions(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Permissions = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_UserId(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->UserId = safe_cast<TValue^>(value);
}

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    bool    isLocalType;
    bool    isSystemType;
    bool    isReturnTypeStub;
    bool    isBindable;
};

TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   2
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    3, // System.ValueType
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, false, false,
    //   3
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, false, false,
    //   4
    L"winsdkfb.CroppingType", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::winsdkfb::CroppingType>,
    2, // System.Enum
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, false, false,
    //   5
    L"winsdkfb.FBLoginButton", L"",
    &ActivateType<::winsdkfb::FBLoginButton>, nullptr, nullptr, nullptr,
    10, // Windows.UI.Xaml.Controls.Button
    0, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, false, false,
    //   6
    L"winsdkfb.FBPermissions", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    1, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, true,  false,
    //   7
    L"winsdkfb.ScaleConverter", L"",
    &ActivateType<::winsdkfb::ScaleConverter>, nullptr, nullptr, nullptr,
    0, // Object
    1, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, false, false,
    //   8
    L"winsdkfb.FacebookDialog", L"",
    &ActivateType<::winsdkfb::FacebookDialog>, nullptr, nullptr, nullptr,
    12, // Windows.UI.Xaml.Controls.UserControl
    1, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, false, false,
    //   9
    L"winsdkfb.ProfilePictureControl", L"",
    &ActivateType<::winsdkfb::ProfilePictureControl>, nullptr, nullptr, nullptr,
    12, // Windows.UI.Xaml.Controls.UserControl
    1, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, false, false,
    //  10
    L"Windows.UI.Xaml.Controls.Button", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    3, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //  11
    L"winsdkfb.ColorLuminosityConverter", L"",
    &ActivateType<::winsdkfb::ColorLuminosityConverter>, nullptr, nullptr, nullptr,
    0, // Object
    3, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    true,  false, false, false,
    //  12
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    3, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //  13
    L"Windows.UI.Xaml.Controls.ContentControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    3, 2, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    3, 2,::Windows::UI::Xaml::Interop::TypeKind::Custom,
    false, false, false, false,
};

UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      2,   //   7
      2,   //   8
      2,   //   9
      2,   //  10
      2,   //  11
      3,   //  12
      3,   //  13
      3,   //  14
      3,   //  15
      3,   //  16
      4,   //  17
      4,   //  18
      4,   //  19
      4,   //  20
      4,   //  21
      5,   //  22
      7,   //  23
      9,   //  24
      9,   //  25
      9,   //  26
      9,   //  27
      9,   //  28
      9,   //  29
      9,   //  30
     10,   //  31
     11,   //  32
     11,   //  33
     12,   //  34
     12,   //  35
     12,   //  36
     13,   //  37
     13,   //  38
     13,   //  39
     14,   //  40
};

struct EnumValueInfo
{
    PCWSTR name;
    int eValue;
};

EnumValueInfo EnumValues[] =
{ 
    L"Square", (int) ::winsdkfb::CroppingType::Square,
    L"Original", (int) ::winsdkfb::CroppingType::Original,
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

MemberInfo MemberInfos[] = 
{
    //   0 - winsdkfb.FBLoginButton.Permissions
    L"Permissions",
    &GetReferenceTypeMember_Permissions<::winsdkfb::FBLoginButton>,
    &SetReferenceTypeMember_Permissions<::winsdkfb::FBLoginButton, ::winsdkfb::FBPermissions>,
    6, // winsdkfb.FBPermissions
    -1,
    false, false, false,
    //   1 - winsdkfb.ProfilePictureControl.CropMode
    L"CropMode",
    &GetValueTypeMember_CropMode<::winsdkfb::ProfilePictureControl, ::winsdkfb::CroppingType>,
    &SetEnumMember_CropMode<::winsdkfb::ProfilePictureControl, ::winsdkfb::CroppingType>,
    4, // winsdkfb.CroppingType
    -1,
    false, false, false,
    //   2 - winsdkfb.ProfilePictureControl.UserId
    L"UserId",
    &GetReferenceTypeMember_UserId<::winsdkfb::ProfilePictureControl>,
    &SetReferenceTypeMember_UserId<::winsdkfb::ProfilePictureControl, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    int typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    for (int lastDotIndex = longMemberName->Length(); lastDotIndex >= 0; lastDotIndex--)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
    }
    return nullptr;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->isSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->isLocalType;
        userType->IsReturnTypeStub = pTypeInfo->isReturnTypeStub;
        userType->IsBindable = pTypeInfo->isBindable;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; i++)
        {
            userType->AddEnumValue(
                ::Platform::StringReference(EnumValues[i].name),
                ::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

